### ISSUE TITLE
getting error on repay - could lead to liquidation.

### ISSUE THREAD

**Issue by conradjohnson** [unl1k3ly/AnchorHODL#10]
will withdraw from UST deposited, but getting error just this AM on repaying - 

Traceback (most recent call last):
  File "/Users/jj/code/AnchorHODL/anchor_loan_repay.py", line 299, in <module>
    keep_loan_safe = keep_loan_safe()
  File "/Users/jj/code/AnchorHODL/anchor_loan_repay.py", line 265, in keep_loan_safe
    loan_repay_tx = execute_loan_repay(repay_amount)
  File "/Users/jj/code/AnchorHODL/anchor_loan_repay.py", line 163, in execute_loan_repay
    result = terra.tx.broadcast(sendtx)
  File "/usr/local/lib/python3.9/site-packages/terra_sdk/client/lcd/api/_base.py", line 29, in decorator
    return instance._run_sync(async_call(instance, *args, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/terra_sdk/client/lcd/api/_base.py", line 13, in _run_sync
    return self._c.loop.run_until_complete(coroutine)
  File "/usr/local/lib/python3.9/site-packages/nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "/usr/local/Cellar/python@3.9/3.9.2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/usr/local/Cellar/python@3.9/3.9.2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/usr/local/lib/python3.9/site-packages/terra_sdk/client/lcd/api/tx.py", line 201, in broadcast
    res = await self._broadcast(tx, "block")
  File "/usr/local/lib/python3.9/site-packages/terra_sdk/client/lcd/api/tx.py", line 157, in _broadcast
    return await self._c._post("/txs", data, raw=True)
  File "/usr/local/lib/python3.9/site-packages/terra_sdk/client/lcd/lcdclient.py", line 255, in _post
    result = await super()._post(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/terra_sdk/client/lcd/lcdclient.py", line 110, in _post
    raise LCDResponseError(message=result.get("error"), response=response)
terra_sdk.exceptions.LCDResponseError: Status 500 - broadcast_tx_commit: error unmarshalling: invalid character '<' looking fo

**Comment by conradjohnson** [comment]
merge fixed.
