### ISSUE TITLE
getting 403 on the service.  heads up to others to check. 

### ISSUE THREAD

**Issue by conradjohnson** [unl1k3ly/AnchorHODL#12]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/terra_sdk/client/lcd/lcdclient.py", line 91, in _get
    result = await response.json(content_type=None)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1113, in json
    return loads(stripped.decode(encoding))
  File "/usr/local/Cellar/python@3.9/3.9.2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads 
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode 
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.9/3.9.2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/uu/code/AnchorHODL/anchor_loan_repay.py", line 56, in <module>
    balance = terra.bank.balance(address=account_address)
  File "/usr/local/lib/python3.9/site-packages/terra_sdk/client/lcd/api/_base.py", line 29, in decorator
    return instance._run_sync(async_call(instance, *args, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/terra_sdk/client/lcd/api/_base.py", line 13, in _run_sync
    return self._c.loop.run_until_complete(coroutine)
  File "/usr/local/lib/python3.9/site-packages/nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "/usr/local/Cellar/python@3.9/3.9.2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/usr/local/Cellar/python@3.9/3.9.2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/usr/local/lib/python3.9/site-packages/terra_sdk/client/lcd/api/bank.py", line 18, in balance
    res = await self._c._get(f"/bank/balances/{address}")
  File "/usr/local/lib/python3.9/site-packages/terra_sdk/client/lcd/lcdclient.py", line 243, in _get
    result = await super()._get(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/terra_sdk/client/lcd/lcdclient.py", line 93, in _get
    raise LCDResponseError(message=str(response.reason), response=response)
terra_sdk.exceptions.LCDResponseError: Status 403 - Forbidden

**Comment by conradjohnson** [comment]
Looks like an issue with lcd.terra.dev - watch your loans.

**Comment by conradjohnson** [comment]
service back up and stable.
